# Generated by Django 5.1.6 on 2025-02-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customUser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
