# Generated by Django 5.1.6 on 2025-02-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customUser", "0002_alter_customuser_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="max_otp_try",
            field=models.IntegerField(default=5),
        ),
    ]
