# Generated by Django 5.1.6 on 2025-02-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_remove_product_category_product_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
