# Generated by Django 5.1.6 on 2025-02-09 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_product_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariation",
            name="image_url",
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
        migrations.AlterField(
            model_name="productvariation",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.CreateModel(
            name="VariationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.ImageField(upload_to="variation_images")),
                ("alt_text", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="store.productvariation",
                    ),
                ),
            ],
        ),
    ]
