# Generated by Django 5.1.6 on 2025-02-09 03:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_remove_productvariation_image_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variationimage",
            old_name="image_url",
            new_name="image",
        ),
    ]
