# Generated by Django 5.1.6 on 2025-02-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_rename_image_url_variationimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariation",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=10, null=True
            ),
        ),
    ]
