# Generated by Django 5.1.6 on 2025-02-09 04:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_alter_productvariation_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image_url",
            new_name="image",
        ),
    ]
