# Generated by Django 5.1.6 on 2025-03-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_cartitem_product_cartitem_product_variation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="product_variation",
            new_name="productVariation",
        ),
    ]
